'''
Description: Vastbase SchemaEditor 兼容 PostgreSQL 9.2
Version: 1.0
Author: GPT助手
Date: 2025-11-22 00:00:00
LastEditors: GPT助手
LastEditTime: 2025-11-22 00:00:00
'''
from django.db.backends.postgresql.schema import (
    DatabaseSchemaEditor as PostgreSQLSchemaEditor,
)


class DatabaseSchemaEditor(PostgreSQLSchemaEditor):
    """
    Vastbase SchemaEditor

    PostgreSQL 9.2 不支持 GENERATED AS IDENTITY，需要降级为 SERIAL/BIGSERIAL。
    """

    def _field_data_type(self, field):
        """
        构建字段类型时，剔除 Django 4.2 默认生成的 IDENTITY 语法。
        """
        data_type = super()._field_data_type(field)
        if not data_type:
            return data_type

        normalized = data_type.upper()
        if "GENERATED BY DEFAULT AS IDENTITY" in normalized or "GENERATED ALWAYS AS IDENTITY" in normalized:
            if "BIGINT" in normalized:
                data_type = data_type.upper().replace(
                    "BIGINT GENERATED BY DEFAULT AS IDENTITY",
                    "BIGSERIAL",
                )
                data_type = data_type.replace(
                    "GENERATED BY DEFAULT AS IDENTITY",
                    "",
                ).strip()
            else:
                data_type = data_type.upper().replace(
                    "INTEGER GENERATED BY DEFAULT AS IDENTITY",
                    "SERIAL",
                )
                data_type = data_type.replace(
                    "GENERATED BY DEFAULT AS IDENTITY",
                    "",
                ).strip()

        return data_type


